import React from 'react';

const Courses = () => {
    return (
        <div className='bg-base-200 p-10'> 
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
            Courses <br/>
        </div>
    );
};

export default Courses;